### ISSUE TITLE
Bash best practices checklist

### ISSUE THREAD

**Issue by j143** [j143/systemds#93]
## checklist

- [x] Always double quote variables, including subshells. No naked `$` signs
     * This rule gets you pretty far. Read http://mywiki.wooledge.org/Quotes for details
- [x] All code goes in a function. Even if it's one function, `main`. 
     * Unless a library script, you can do global script settings and call `main`. That's it.
     * Avoid global variables. Though when defining constants use `readonly`
- [ ] Always have a `main` function for runnable scripts, called with `main` or `main "$@"`
     * If script is also usable as library, call it using `[[ "$0" == "$BASH_SOURCE" ]] && main "$@"`
- [ ] Always use `local` when setting variables, unless there is reason to use `declare`
     * Exception being rare cases when you are intentionally setting a variable in an outer scope.
- [x] Variable names should be lowercase unless exported to environment.
- [x] Always use `set -eo pipefail`. Fail fast and be aware of exit codes. 
     * Use `|| true` on programs that you intentionally let exit non-zero.
- [x] Never use deprecated style. Most notably:
     * Define functions as `myfunc() { ... }`, not `function myfunc { ... }`
     * Always use `[[` instead of `[` or `test`
     * Never use backticks, use `$( ... )`
     * See http://wiki.bash-hackers.org/scripting/obsolete for more
- [x] Prefer absolute paths (leverage $PWD), always qualify relative paths with `./`.
- [ ] Always use `declare` and name variable arguments at the top of functions that are more than 2-lines
     * Example: `declare arg1="$1" arg2="$2"`
     * The exception is when defining variadic functions. See below.
- [x] Use `mktemp` for temporary files, always cleanup with a `trap`.
- [x] Warnings and errors should go to STDERR, anything parsable should go to STDOUT.
- [ ] Try to localize `shopt` usage and disable option when finished.

https://google.github.io/styleguide/shellguide.html

https://github.com/j143/bashstyle
